#modified from Yoel oilcane biorefinery
import biosteam as bst

def load_process_settings():
    GWP= 'GWP100'
    settings = bst.settings
    bst.process_tools.default_utilities()
    settings.CEPCI = 803.2 # 2023 https://www.toweringskills.com/financial-analysis/cost-indices/ accessed 9/27/2023
    settings.define_impact_indicator(key=GWP, units='kg*CO2e')
    steam_utility = settings.get_agent('high_pressure_steam')
    steam_utility.heat_transfer_efficiency = 0.9
    steam_utility.regeneration_price = 0.03
    steam_utility.T = 529.2
    steam_utility.P = 44e5
    # steam_utility.T = 310+273.15
    # steam_utility.P = 1e7
    # lps = settings.get_agent('low_pressure_steam')
    # lps.T = 412.189
    # mps = settings.get_agent('medium_pressure_steam')
    # mps.T = 233 +273.15
    settings.get_agent("low_pressure_steam").regeneration_price = 0.03
    settings.get_agent("medium_pressure_steam").regeneration_price = 0.03
    bst.PowerUtility.price = 0.065  # Electricity price [USD/hr], based on lipidcane biorefinery #TODO: change
    # Steam, cooling water, and chilled water are regenerated by
    # on-site facilities. The regeneration and heat transfer
    # prices are given accounted for by the capital cost and
    # electricity consumption of these facilities
    settings.get_agent('cooling_water').regeneration_price = 0
    settings.get_agent('chilled_water').heat_transfer_price = 0
    # bst.settings.define_impact_indicator(key=GWP, units='kg*CO2e')